<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise-then方法</title>
</head>

<body>
    <script>
        const p = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('用户数据');
                // reject('error');
            }, 1000);
        });
        /* 
            then 方法的返回结果是Promise对象
            对象的状态（PromiseState）由回调函数的【返回值】决定（成功：fulfilled、resolved;失败：rejected）
        */
        const result = p.then(value => {
            console.log('value:', value);
            /*--------------------【1.非Promise对象】--------------------
                返回值如果不是 Promise 对象，
                那么 result 的状态（PromiseState）为成功，
                返回值会被作为 result 的值（PromiseResult）
            */
            return value;
            /*--------------------【2.Promise对象】--------------------
                如果返回值是一个 Promise 对象，
                则根据 Promise 对象的状态，决定 result 的状态
            */
            // return new Promise((resolve, reject) => {
            //     // 此处的值也将作为，result 的值（PromiseResult）
            //     // resolve('123');
            //     reject('error');
            // });
            /*--------------------【3.抛出错误】--------------------
                result 状态为失败
                抛出的错误提示将作为 result 的值
            */
            // throw new Error('出错了!');
            // throw '出错了!';
        }, reason => {
            console.warn(reason);
        });
        console.log('result:', result);

        /* 
            由于 then 方法的的返回值也是 Promise 对象
            是的 then 可以实现【链式调用】
            链式调用可以解决【回调地狱】
        */
        p.then((value, reason) => {

        }).then((value, reason) => {
            
        }).then((value, reason) => {
            
        });
    </script>
</body>

</html>